### ISSUE TITLE
Failed to open ply file for reading: /home/davidxu/bunny.points.ply

### ISSUE THREAD

**Issue by justin5718** [DavidXu-JJ/PoissonRecon_GPU#1]
the error log is mentioned as above when l ready to compile the code. Can you tell me where to find the ply file or how to get it, thank you

**Comment by DavidXu-JJ** [comment]
Just send whatever ply file with normal information you like to this program. I don't think it's very hard to change the file path and find an interesting point cloud file with normal. This is not even a technical problem. Issue closed.

**Comment by DavidXu-JJ** [comment]
By the way, I'm sorry for my late reply.

**Comment by DavidXu-JJ** [comment]
Just send whatever ply file with normal information you like to this program. I don't think it's very hard to change the file path and find an interesting point cloud file with normal. Issue closed.

BTW: If you want to get some results like in README, please view the original Kazhdan's release page to find the pcd file.(https://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version16.01/)

Sorry for the late reply.

Best,
Jingwei

**Comment by justin5718** [comment]
OK thx
